/*
//syntax
namespace namespace_name1 { 
    export namespace namespace_name2 {
       export class class_name {    } 
    } 
 }
    */


 /*
 //You can access members of nested namespace by using the dot (.) operator as follows −
 FileName : Invoice.ts  
 namespace tutorialPoint { 
    export namespace invoiceApp { 
       export class Invoice { 
          public calculateDiscount(price: number) { 
             return price * .40; 
          } 
       } 
    } 
 } 
 FileName: InvoiceTest.ts 
 
 /// <reference path = "Invoice.ts" />
 var invoice = new tutorialPoint.invoiceApp.Invoice(); 
 console.log(invoice.calculateDiscount(500));
 */


 // JavaScript code(app.js).
 //Generated by typescript 1.8.10
var tutorialPoint;
(function (tutorialPoint) {
   var invoiceApp;
   (function (invoiceApp) {
      var Invoice = (function () {
         function Invoice() {
         }
         Invoice.prototype.calculateDiscount = function (price) {
            return price * .40;
         };
         return Invoice;
      }());
      invoiceApp.Invoice = Invoice;
   })(invoiceApp = tutorialPoint.invoiceApp || (tutorialPoint.invoiceApp = {}));
	
})(tutorialPoint || (tutorialPoint = {}));
/// <reference path = "Invoice.ts" />

var invoice = new tutorialPoint.invoiceApp.Invoice();
console.log(invoice.calculateDiscount(500));
